"""Add RecoveryDecisionRecord and idempotency to RecoveryAction

Revision ID: 5d4ad05965f5
Revises: 8ddada73c291
Create Date: 2026-08-25 23:46:34.636542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4ad05965f5'
down_revision: Union[str, Sequence[str], None] = '8ddada73c291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('classified_by', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('requires_llm', sa.Boolean(), nullable=False),
    sa.Column('next_action', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['recovery_strategies.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_decisions_transaction_id'), 'recovery_decisions', ['transaction_id'], unique=False)
    op.add_column('recovery_actions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('recovery_actions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_recovery_actions_idempotency_key'), 'recovery_actions', ['idempotency_key'], unique=True)
    op.drop_column('recovery_actions', 'outcome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_actions', sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_recovery_actions_idempotency_key'), table_name='recovery_actions')
    op.drop_column('recovery_actions', 'idempotency_key')
    op.drop_column('recovery_actions', 'status')
    op.drop_index(op.f('ix_recovery_decisions_transaction_id'), table_name='recovery_decisions')
    op.drop_table('recovery_decisions')
    # ### end Alembic commands ###
