"""remove_unique_name

Revision ID: 8ddada73c291
Revises: a13be9db8181
Create Date: 2026-08-24 14:53:38.256623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddada73c291'
down_revision: Union[str, Sequence[str], None] = 'a13be9db8181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_strategies_name'), table_name='recovery_strategies')
    op.create_index(op.f('ix_recovery_strategies_name'), 'recovery_strategies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_strategies_name'), table_name='recovery_strategies')
    op.create_index(op.f('ix_recovery_strategies_name'), 'recovery_strategies', ['name'], unique=True)
    # ### end Alembic commands ###
