"""Initial schema

Revision ID: a13be9db8181
Revises: 
Create Date: 2026-08-24 14:50:40.206473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13be9db8181'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_reasons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('decline_code', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_reasons_decline_code'), 'failure_reasons', ['decline_code'], unique=True)
    op.create_table('recovery_strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('applicable_bucket', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_strategies_name'), 'recovery_strategies', ['name'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('gateway_used', sa.String(), nullable=False),
    sa.Column('decline_code', sa.String(), nullable=True),
    sa.Column('decline_message', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_decline_code'), 'payment_attempts', ['decline_code'], unique=False)
    op.create_index(op.f('ix_payment_attempts_transaction_id'), 'payment_attempts', ['transaction_id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('classified_by', sa.String(), nullable=False),
    sa.Column('predicted_bucket', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['recovery_strategies.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_classified_by'), 'recovery_actions', ['classified_by'], unique=False)
    op.create_index(op.f('ix_recovery_actions_transaction_id'), 'recovery_actions', ['transaction_id'], unique=False)
    op.create_table('strategy_performance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['recovery_strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'strategy_id', name='uix_bucket_strategy')
    )
    op.create_index(op.f('ix_strategy_performance_bucket'), 'strategy_performance', ['bucket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_performance_bucket'), table_name='strategy_performance')
    op.drop_table('strategy_performance')
    op.drop_index(op.f('ix_recovery_actions_transaction_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_classified_by'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_payment_attempts_transaction_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_decline_code'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_recovery_strategies_name'), table_name='recovery_strategies')
    op.drop_table('recovery_strategies')
    op.drop_index(op.f('ix_failure_reasons_decline_code'), table_name='failure_reasons')
    op.drop_table('failure_reasons')
    # ### end Alembic commands ###
