import json
import httpx
from typing import Dict, Any
from app.llm.base import LLMProvider
from app.llm.models import LLMResult
from app.core.config import settings

class AnthropicProvider(LLMProvider):
    """
    Anthropic Claude LLM Provider using direct HTTP API (httpx).
    Compatible with claude-3-5-sonnet-20241022, claude-3-haiku-20240307, etc.
    """
    def __init__(self):
        if not settings.ANTHROPIC_API_KEY:
            raise ValueError("ANTHROPIC_API_KEY is not configured")
        self.api_key: str = settings.ANTHROPIC_API_KEY
        self.model_name = settings.LLM_MODEL if "claude" in settings.LLM_MODEL else "claude-3-haiku-20240307"
        self.timeout = float(settings.LLM_TIMEOUT_SECONDS)

    def classify(self, context: Dict[str, Any]) -> LLMResult:
        system_prompt = (
            "You are a strict JSON-only classification model for a payment recovery engine. "
            "Your job is to disambiguate ambiguous bank failure codes.\n\n"
            "Bucket A = customer-side failure (e.g. insufficient funds, expired card).\n"
            "Bucket B = bank/network ambiguity (e.g. timeout, processing error).\n"
            "Bucket C MUST NEVER be generated by you. It is for regulatory rules only.\n\n"
            "You must return STRICT JSON ONLY exactly matching this schema:\n"
            "{\n"
            "  \"bucket\": \"A\" or \"B\",\n"
            "  \"confidence\": float between 0 and 1,\n"
            "  \"reasoning\": \"<= 80 words\"\n"
            "}\n"
            "No markdown fences, no surrounding explanation."
        )
        
        user_prompt = f"Context:\n{json.dumps(context, indent=2, default=str)}"
        
        url = "https://api.anthropic.com/v1/messages"
        headers: Dict[str, str] = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json"
        }
        payload = {
            "model": self.model_name,
            "max_tokens": 200,
            "system": system_prompt,
            "messages": [
                {"role": "user", "content": user_prompt}
            ]
        }
        
        try:
            with httpx.Client(timeout=self.timeout) as client:
                response = client.post(url, headers=headers, json=payload)
                response.raise_for_status()
                data = response.json()
                
            content = data["content"][0]["text"].strip()
            # Clean possible markdown wrap if returned
            if content.startswith("```json"):
                content = content[7:]
            if content.startswith("```"):
                content = content[3:]
            if content.endswith("```"):
                content = content[:-3]
            content = content.strip()
            
            parsed = json.loads(content)
            
            return LLMResult(
                bucket=parsed["bucket"],
                confidence=float(parsed["confidence"]),
                reasoning=parsed["reasoning"],
                model=self.model_name,
                provider="anthropic"
            )
        except httpx.TimeoutException as e:
            raise RuntimeError("Anthropic API timeout") from e
        except httpx.HTTPStatusError as e:
            raise RuntimeError(f"Anthropic API error: {e.response.status_code}") from e
        except json.JSONDecodeError as e:
            raise ValueError("Invalid JSON returned by Claude LLM") from e
        except KeyError as e:
            raise ValueError(f"Missing expected field in Claude LLM JSON: {e}") from e
        except Exception as e:
            raise RuntimeError(f"Unexpected Claude LLM failure: {str(e)}") from e
