import json
from typing import Dict, Any
import httpx
from app.llm.base import LLMProvider
from app.llm.models import LLMResult
from app.core.config import settings

class GeminiProvider(LLMProvider):
    def __init__(self):
        self.api_key = settings.GEMINI_API_KEY
        self.model_name = settings.LLM_MODEL or "gemini-2.5-flash"
        self.timeout = float(settings.LLM_TIMEOUT_SECONDS or 10)
        
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY is not configured")

    def classify(self, context: Dict[str, Any]) -> LLMResult:
        # Check simulation / fault injection flags
        if context.get("force_llm_failure"):
            raise RuntimeError("Simulated LLM failure")
            
        if context.get("force_llm_c_prediction"):
            return LLMResult(
                bucket="C",
                confidence=0.99,
                reasoning="Forced LLM Bucket C prediction for safety testing",
                model=self.model_name,
                provider="gemini"
            )

        system_prompt = (
            "You are a strict JSON-only classification model for the Failure-Aware Revenue Recovery Engine (FARRE).\n"
            "Your job is to disambiguate ambiguous bank failure codes.\n\n"
            "Bucket A = customer-side failure (e.g. insufficient funds, expired card).\n"
            "Bucket B = bank/network ambiguity (e.g. timeout, processing error, generic decline).\n"
            "Bucket C MUST NEVER be generated by you. It is for regulatory rules only.\n\n"
            "You must return STRICT JSON ONLY exactly matching this schema:\n"
            "{\n"
            "  \"bucket\": \"A\" or \"B\",\n"
            "  \"confidence\": float between 0.0 and 1.0,\n"
            "  \"reasoning\": \"Concise reasoning <= 80 words\"\n"
            "}\n"
            "No markdown fences, no surrounding explanation."
        )
        
        user_prompt = f"Context:\n{json.dumps(context, indent=2, default=str)}"
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"
        
        payload = {
            "contents": [{"parts": [{"text": user_prompt}]}],
            "systemInstruction": {"parts": [{"text": system_prompt}]},
            "generationConfig": {
                "response_mime_type": "application/json",
                "temperature": 0.1
            }
        }
        
        try:
            with httpx.Client(timeout=self.timeout) as client:
                response = client.post(url, json=payload)
                
            if response.status_code != 200:
                raise RuntimeError(f"Gemini API returned HTTP {response.status_code}")
                
            resp_data = response.json()
            candidates = resp_data.get("candidates", [])
            if not candidates:
                raise ValueError("Empty candidate response from Gemini API")
                
            content_part = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
            if not content_part:
                raise ValueError("Empty content from Gemini API")
                
            parsed = json.loads(content_part)
            
            bucket = str(parsed.get("bucket", "")).strip().upper()
            confidence = float(parsed.get("confidence", 0.0))
            reasoning = str(parsed.get("reasoning", "")).strip()
            
            if bucket not in ("A", "B"):
                if bucket == "C":
                    raise ValueError("Safety Violation: LLM output Bucket C")
                raise ValueError(f"Invalid bucket in Gemini response: {bucket}")
                
            if not (0.0 <= confidence <= 1.0):
                raise ValueError(f"Invalid confidence score: {confidence}")
                
            return LLMResult(
                bucket=bucket,
                confidence=confidence,
                reasoning=reasoning,
                model=self.model_name,
                provider="gemini"
            )
            
        except httpx.TimeoutException as e:
            raise RuntimeError("Gemini API request timed out") from e
        except httpx.HTTPError as e:
            raise RuntimeError(f"Gemini API network error: {e}") from e
        except json.JSONDecodeError as e:
            raise ValueError("Invalid JSON returned by Gemini API") from e
        except KeyError as e:
            raise ValueError(f"Missing expected field in Gemini response: {e}") from e
        except Exception as e:
            if "Safety Violation: LLM output Bucket C" in str(e):
                raise
            raise RuntimeError(f"Unexpected LLM classification failure: {str(e)}") from e
